### ISSUE TITLE
MCDR开启rcon时here不能解析1.16新dimension数据格式报错

### ISSUE THREAD

**Issue by Flyky** [TISUnion/Here#10]
如题，here未能完全适配1.16
**MCDR未开启rcon时没有问题，可以适配解析1.16新dimension数据项**
**MCDR开启rcon时无法适配解析1.16新dimension数据项**
![](https://s1.ax1x.com/2020/06/07/tgvL90.png)

**Comment by dogdie233** [comment]
又是屑mojang牌json的锅
