### ISSUE TITLE
donnt work sometimes

### ISSUE THREAD

**Issue by kafuuchino-desu** [TISUnion/Here#2]
![image](https://user-images.githubusercontent.com/33673786/49453177-93ab0980-f81d-11e8-8ce7-16216069c584.png)

**Comment by Pandaria98** [comment]
Won't work exactly when player name contains underline, please check the regex pattern

**Comment by nathan21hz** [comment]
That not happen in my test server...
(at least not caused by underline or minus sign) 
![default](https://user-images.githubusercontent.com/25732174/49482209-2329da00-f869-11e8-8194-4c57dab66460.PNG)
