### ISSUE TITLE
关于xaero's world map的路径点添加的一些问题

### ISSUE THREAD

**Issue by yuyi2439** [TISUnion/Here#29]
Here版本：v1.2.2
mc版本：1.20.1
mcdr版本：2.9.1
xaero's world map版本：1.30.6

我在使用!!here命令后，得到的[+X]，点击它并没有任何响应，我觉得这是个问题

我找到一个解决方案：向点击这个地方的玩家发送xaero-waypoint:(路径全名):(路径缩写):(X):(Y):(Z):(颜色0-15，xwp添加路径点的界面里有):(是否设置朝向，有的时候朝向设置为空，但是分享数据中的朝向仍不为0):(朝向):Internal-overworld-waypoints(overworld可以换成the-nether或the-end)
例子：xaero-waypoint:家:家:-544:70:-113:0:false:0:Internal-overworld-waypoints

如果是在这个插件里使用，可以这样：直接tellraw给发送者应该就可以(mcdr应该有函数，不过我忘了)
xaero-waypoint:{玩家名}的位置:H(Here的首字母):{X}:{Y}:{Z}:0:false:0:Internal-{世界名称}-waypoints(世界名称：overworld或the-nether或the-end)

**Comment by Fallen-Breath** [comment]
请先确定是否与 https://github.com/Fallen-Breath/MCDReforged/issues/203 相关

此外，“向点击这个地方的玩家发送”这并不可行。如果实现方式为向“按钮”添加 run_command 的 click event，如果用 `/tellraw` 指令，则依赖玩家具有足够权限 / 如果使用发送信息的方式，则见上述 MCDR issue
