### ISSUE TITLE
Better dimension display

### ISSUE THREAD

**Issue by 66Leo66** [TISUnion/Here#8]
显示与玩家客户端语言文件对应的维度名称，可以使用json文本的translate(对象？)实现。

**Comment by Fallen-Breath** [comment]
这个可以的，之后试试

**Comment by 66Leo66** [comment]
其实我有试着去实现这个功能，功能可以实现但是出了一些奇奇怪怪的 特性 ，所以无奈只好（无限期）搁置改代码的计划。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Fallen_Breath"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月3日(星期天) 晚上9:28
收件人:&nbsp;"TISUnion/Here"<Here@noreply.github.com&gt;;
抄送:&nbsp;"66Leo66"<1463359949@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TISUnion/Here] Better dimension display (#8)





 
这个可以的，之后试试
